project:
  type: website

website:
  title: "PeDrOOM Blog"
  description: "Esse é o blog pessoal do Pedro Lima"
  navbar:
    right:
      - CV.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/cruz-ml-pedro
      - icon: linkedin
        href: https://www.linkedin.com/in/pedro-lima-8a9356268/
format:
  html:
    theme: minty
    css: styles.css

editor: visual

